// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | TextBlockSlice
  | ImageBlockSlice
  | FooterSlice
  | SectionTextSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Options field in *Article*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Seleccione tipo de articulo para su visualización
   * - **API ID Path**: article.options
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  options: prismic.SelectField<
    "articuloComun" | "articuloDiario" | "articuloFoto"
  >;

  /**
   * Fecha Publicación field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.fecha_publicacion
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  fecha_publicacion: prismic.DateField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Content for Copyright documents
 */
interface CopyrightDocumentData {
  /**
   * Text field in *Copyright*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *Copyright*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Copyright document from Prismic
 *
 * - **API ID**: `copyright`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CopyrightDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CopyrightDocumentData>,
    "copyright",
    Lang
  >;

/**
 * Content for Global Settings documents
 */
interface GlobalSettingsDocumentData {
  /**
   * WhatsappNumber field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.whatsappnumber
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsappnumber: prismic.KeyTextField;
}

/**
 * Global Settings document from Prismic
 *
 * - **API ID**: `global_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSettingsDocumentData>,
    "global_settings",
    Lang
  >;

/**
 * Item in *Navigation → NavLeft*
 */
export interface NavigationDocumentDataNavleftItem {
  /**
   * Name field in *Navigation → NavLeft*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navleft[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *Navigation → NavLeft*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navleft[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation → NavRight*
 */
export interface NavigationDocumentDataNavrightItem {
  /**
   * Name field in *Navigation → NavRight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navright[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *Navigation → NavRight*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navright[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type NavigationDocumentDataSlicesSlice = never;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * LogoImage field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logoimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoimage: prismic.ImageField<never>;

  /**
   * LogoLink field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logolink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logolink: prismic.LinkField;

  /**
   * NavLeft field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navleft[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navleft: prismic.GroupField<Simplify<NavigationDocumentDataNavleftItem>>;

  /**
   * NavRight field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navright[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navright: prismic.GroupField<Simplify<NavigationDocumentDataNavrightItem>>;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | AboutMeSlice
  | TextBlockSlice
  | HeroSlice
  | SectionTextSlice
  | PictureButtonSlice
  | SectionCheckSlice
  | SectionContentSlice
  | FooterSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ArticleDocument
  | CopyrightDocument
  | GlobalSettingsDocument
  | NavigationDocument
  | PageDocument;

/**
 * Primary content in *AboutMe → Default → Primary*
 */
export interface AboutMeSliceDefaultPrimary {
  /**
   * Title field in *AboutMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * ImagePlant field in *AboutMe → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.default.primary.imageplant
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageplant: prismic.ImageField<never>;

  /**
   * Description field in *AboutMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *AboutMe → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutMe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutMeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutMe*
 */
type AboutMeSliceVariation = AboutMeSliceDefault;

/**
 * AboutMe Shared Slice
 *
 * - **API ID**: `about_me`
 * - **Description**: AboutMe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSlice = prismic.SharedSlice<
  "about_me",
  AboutMeSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * ImagePlant field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.imageplant
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageplant: prismic.ImageField<never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Image field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageBlock → ImageText → Primary*
 */
export interface ImageBlockSliceImageTextPrimary {
  /**
   * Title field in *ImageBlock → ImageText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.imageText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *ImageBlock → ImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.imageText.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageText variation for ImageBlock Slice
 *
 * - **API ID**: `imageText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceImageText = prismic.SharedSliceVariation<
  "imageText",
  Simplify<ImageBlockSliceImageTextPrimary>,
  never
>;

/**
 * Primary content in *ImageBlock → ImageParagraph → Primary*
 */
export interface ImageBlockSliceImageParagraphPrimary {
  /**
   * Subtitle field in *ImageBlock → ImageParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.imageParagraph.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Image field in *ImageBlock → ImageParagraph → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.imageParagraph.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageParagraph variation for ImageBlock Slice
 *
 * - **API ID**: `imageParagraph`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceImageParagraph = prismic.SharedSliceVariation<
  "imageParagraph",
  Simplify<ImageBlockSliceImageParagraphPrimary>,
  never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation =
  | ImageBlockSliceDefault
  | ImageBlockSliceImageText
  | ImageBlockSliceImageParagraph;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Primary content in *PictureButton → Default → Primary*
 */
export interface PictureButtonSliceDefaultPrimary {
  /**
   * Color field in *PictureButton → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Primary content in *PictureButton → Items*
 */
export interface PictureButtonSliceDefaultItem {
  /**
   * Image field in *PictureButton → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * StylesCard field in *PictureButton → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Estilos de tarjeta
   * - **API ID Path**: picture_button.items[].stylescard
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  stylescard: prismic.SelectField<
    "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
  >;

  /**
   * Text field in *PictureButton → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.TitleField;

  /**
   * Link field in *PictureButton → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for PictureButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PictureButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PictureButtonSliceDefaultPrimary>,
  Simplify<PictureButtonSliceDefaultItem>
>;

/**
 * Primary content in *PictureButton → SameStyle → Primary*
 */
export interface PictureButtonSliceSameStylePrimary {
  /**
   * Color field in *PictureButton → SameStyle → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.sameStyle.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * BgImage field in *PictureButton → SameStyle → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.sameStyle.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgimage: prismic.ImageField<never>;
}

/**
 * Primary content in *PictureButton → Items*
 */
export interface PictureButtonSliceSameStyleItem {
  /**
   * Image field in *PictureButton → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *PictureButton → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.TitleField;

  /**
   * Link field in *PictureButton → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_button.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * SameStyle variation for PictureButton Slice
 *
 * - **API ID**: `sameStyle`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PictureButtonSliceSameStyle = prismic.SharedSliceVariation<
  "sameStyle",
  Simplify<PictureButtonSliceSameStylePrimary>,
  Simplify<PictureButtonSliceSameStyleItem>
>;

/**
 * Slice variation for *PictureButton*
 */
type PictureButtonSliceVariation =
  | PictureButtonSliceDefault
  | PictureButtonSliceSameStyle;

/**
 * PictureButton Shared Slice
 *
 * - **API ID**: `picture_button`
 * - **Description**: PictureButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PictureButtonSlice = prismic.SharedSlice<
  "picture_button",
  PictureButtonSliceVariation
>;

/**
 * Primary content in *SectionCheck → Default → Primary*
 */
export interface SectionCheckSliceDefaultPrimary {
  /**
   * Text field in *SectionCheck → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.TitleField;

  /**
   * Color field in *SectionCheck → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * Image field in *SectionCheck → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *SectionCheck → Items*
 */
export interface SectionCheckSliceDefaultItem {
  /**
   * Title field in *SectionCheck → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Texto Modal field in *SectionCheck → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.items[].texto_modal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_modal: prismic.RichTextField;

  /**
   * Description field in *SectionCheck → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *SectionCheck → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_check.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for SectionCheck Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionCheckSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionCheckSliceDefaultPrimary>,
  Simplify<SectionCheckSliceDefaultItem>
>;

/**
 * Slice variation for *SectionCheck*
 */
type SectionCheckSliceVariation = SectionCheckSliceDefault;

/**
 * SectionCheck Shared Slice
 *
 * - **API ID**: `section_check`
 * - **Description**: SectionCheck
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionCheckSlice = prismic.SharedSlice<
  "section_check",
  SectionCheckSliceVariation
>;

/**
 * Primary content in *SectionContent → Default → Primary*
 */
export interface SectionContentSliceDefaultPrimary {
  /**
   * BgColor field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.bgcolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  bgcolor: prismic.ColorField;

  /**
   * ImageLeft field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.imageleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageleft: prismic.ImageField<never>;

  /**
   * BgLeft field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.bgleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgleft: prismic.ImageField<never>;

  /**
   * TitleLeft field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.titleleft
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleleft: prismic.TitleField;

  /**
   * DescripcionLeft field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.descripcionleft
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcionleft: prismic.RichTextField;

  /**
   * TextButton field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.textbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textbutton: prismic.KeyTextField;

  /**
   * LinkButton field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;
}

/**
 * Primary content in *SectionContent → Items*
 */
export interface SectionContentSliceDefaultItem {
  /**
   * Title field in *SectionContent → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *SectionContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * TextButton field in *SectionContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.items[].textbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textbutton: prismic.KeyTextField;

  /**
   * LinkButton field in *SectionContent → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.items[].linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * Image field in *SectionContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SectionContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionContentSliceDefaultPrimary>,
  Simplify<SectionContentSliceDefaultItem>
>;

/**
 * Slice variation for *SectionContent*
 */
type SectionContentSliceVariation = SectionContentSliceDefault;

/**
 * SectionContent Shared Slice
 *
 * - **API ID**: `section_content`
 * - **Description**: SectionContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionContentSlice = prismic.SharedSlice<
  "section_content",
  SectionContentSliceVariation
>;

/**
 * Primary content in *SectionText → Default → Primary*
 */
export interface SectionTextSliceDefaultPrimary {
  /**
   * ImageLeft field in *SectionText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.default.primary.imageleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageleft: prismic.ImageField<never>;

  /**
   * ImageRight field in *SectionText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.default.primary.imageright
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageright: prismic.ImageField<never>;

  /**
   * TextFirst field in *SectionText → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.default.primary.textfirst
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textfirst: prismic.TitleField;

  /**
   * TextSecond field in *SectionText → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.default.primary.textsecond
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textsecond: prismic.TitleField;

  /**
   * ColorBg field in *SectionText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.default.primary.colorbg
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  colorbg: prismic.ColorField;
}

/**
 * Default variation for SectionText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SectionText → Static → Primary*
 */
export interface SectionTextSliceStaticPrimary {
  /**
   * ImageLeft field in *SectionText → Static → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.static.primary.imageleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageleft: prismic.ImageField<never>;

  /**
   * ImageRight field in *SectionText → Static → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.static.primary.imageright
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageright: prismic.ImageField<never>;

  /**
   * TextFirst field in *SectionText → Static → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.static.primary.textfirst
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textfirst: prismic.TitleField;

  /**
   * ColorBg field in *SectionText → Static → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.static.primary.colorbg
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  colorbg: prismic.ColorField;
}

/**
 * Static variation for SectionText Slice
 *
 * - **API ID**: `static`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSliceStatic = prismic.SharedSliceVariation<
  "static",
  Simplify<SectionTextSliceStaticPrimary>,
  never
>;

/**
 * Primary content in *SectionText → ImageWithFrase → Primary*
 */
export interface SectionTextSliceImageWithFrasePrimary {
  /**
   * Title field in *SectionText → ImageWithFrase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithFrase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * ImageCentral field in *SectionText → ImageWithFrase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithFrase.primary.imagecentral
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagecentral: prismic.ImageField<never>;

  /**
   * ImageLeft field in *SectionText → ImageWithFrase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithFrase.primary.imageleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageleft: prismic.ImageField<never>;

  /**
   * ImageRight field in *SectionText → ImageWithFrase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithFrase.primary.imageright
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageright: prismic.ImageField<never>;

  /**
   * TextFirst field in *SectionText → ImageWithFrase → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithFrase.primary.textfirst
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textfirst: prismic.TitleField;
}

/**
 * ImageWithFrase variation for SectionText Slice
 *
 * - **API ID**: `imageWithFrase`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSliceImageWithFrase = prismic.SharedSliceVariation<
  "imageWithFrase",
  Simplify<SectionTextSliceImageWithFrasePrimary>,
  never
>;

/**
 * Primary content in *SectionText → ImageWithTwoFrases → Primary*
 */
export interface SectionTextSliceImageWithTwoFrasesPrimary {
  /**
   * ImageCentral field in *SectionText → ImageWithTwoFrases → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithTwoFrases.primary.imagecentral
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagecentral: prismic.ImageField<never>;

  /**
   * Title field in *SectionText → ImageWithTwoFrases → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithTwoFrases.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *SectionText → ImageWithTwoFrases → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithTwoFrases.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * ImagePlant field in *SectionText → ImageWithTwoFrases → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.imageWithTwoFrases.primary.imageplant
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageplant: prismic.ImageField<never>;
}

/**
 * ImageWithTwoFrases variation for SectionText Slice
 *
 * - **API ID**: `imageWithTwoFrases`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSliceImageWithTwoFrases = prismic.SharedSliceVariation<
  "imageWithTwoFrases",
  Simplify<SectionTextSliceImageWithTwoFrasesPrimary>,
  never
>;

/**
 * Primary content in *SectionText → StaticLarge → Primary*
 */
export interface SectionTextSliceStaticLargePrimary {
  /**
   * ImageLeft field in *SectionText → StaticLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.staticLarge.primary.imageleft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageleft: prismic.ImageField<never>;

  /**
   * ImageRight field in *SectionText → StaticLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.staticLarge.primary.imageright
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageright: prismic.ImageField<never>;

  /**
   * TextFirst field in *SectionText → StaticLarge → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.staticLarge.primary.textfirst
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textfirst: prismic.TitleField;

  /**
   * ColorBg field in *SectionText → StaticLarge → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_text.staticLarge.primary.colorbg
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  colorbg: prismic.ColorField;
}

/**
 * StaticLarge variation for SectionText Slice
 *
 * - **API ID**: `staticLarge`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSliceStaticLarge = prismic.SharedSliceVariation<
  "staticLarge",
  Simplify<SectionTextSliceStaticLargePrimary>,
  never
>;

/**
 * Slice variation for *SectionText*
 */
type SectionTextSliceVariation =
  | SectionTextSliceDefault
  | SectionTextSliceStatic
  | SectionTextSliceImageWithFrase
  | SectionTextSliceImageWithTwoFrases
  | SectionTextSliceStaticLarge;

/**
 * SectionText Shared Slice
 *
 * - **API ID**: `section_text`
 * - **Description**: SectionText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTextSlice = prismic.SharedSlice<
  "section_text",
  SectionTextSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ingrese el texto
   * - **API ID Path**: text_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → TitleText → Primary*
 */
export interface TextBlockSliceTitleTextPrimary {
  /**
   * Title field in *Text → TitleText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.titleText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Text → TitleText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.titleText.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * TitleText variation for Text Slice
 *
 * - **API ID**: `titleText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceTitleText = prismic.SharedSliceVariation<
  "titleText",
  Simplify<TextBlockSliceTitleTextPrimary>,
  never
>;

/**
 * Primary content in *Text → AuthorOLD → Primary*
 */
export interface TextBlockSliceAuthorTitleTextPrimary {
  /**
   * Author field in *Text → AuthorOLD → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.authorTitleText.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Title field in *Text → AuthorOLD → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.authorTitleText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Text → AuthorOLD → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.authorTitleText.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * AuthorOLD variation for Text Slice
 *
 * - **API ID**: `authorTitleText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceAuthorTitleText = prismic.SharedSliceVariation<
  "authorTitleText",
  Simplify<TextBlockSliceAuthorTitleTextPrimary>,
  never
>;

/**
 * Primary content in *Text → Firma → Primary*
 */
export interface TextBlockSliceFirmaPrimary {
  /**
   * Text field in *Text → Firma → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.firma.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Firma variation for Text Slice
 *
 * - **API ID**: `firma`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceFirma = prismic.SharedSliceVariation<
  "firma",
  Simplify<TextBlockSliceFirmaPrimary>,
  never
>;

/**
 * Primary content in *Text → ShortTextDiario → Primary*
 */
export interface TextBlockSliceShortTextDiarioPrimary {
  /**
   * Title field in *Text → ShortTextDiario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.shortTextDiario.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Text → ShortTextDiario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.shortTextDiario.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * ShortTextDiario variation for Text Slice
 *
 * - **API ID**: `shortTextDiario`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceShortTextDiario = prismic.SharedSliceVariation<
  "shortTextDiario",
  Simplify<TextBlockSliceShortTextDiarioPrimary>,
  never
>;

/**
 * Primary content in *Text → contactText → Primary*
 */
export interface TextBlockSliceContactTextPrimary {
  /**
   * Name field in *Text → contactText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Email field in *Text → contactText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Text → contactText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Residence field in *Text → contactText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.residence
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  residence: prismic.KeyTextField;

  /**
   * Message field in *Text → contactText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * ImageBorder1 field in *Text → contactText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.imageborder
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageborder: prismic.ImageField<never>;

  /**
   * ImageBorder2 field in *Text → contactText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactText.primary.imageborder2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageborder2: prismic.ImageField<never>;
}

/**
 * contactText variation for Text Slice
 *
 * - **API ID**: `contactText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceContactText = prismic.SharedSliceVariation<
  "contactText",
  Simplify<TextBlockSliceContactTextPrimary>,
  never
>;

/**
 * Primary content in *Text → ContactTurno → Primary*
 */
export interface TextBlockSliceContactTurnoPrimary {
  /**
   * Titulo field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Email field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Name field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Age field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.age
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  age: prismic.KeyTextField;

  /**
   * Perdida field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.perdida
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  perdida: prismic.KeyTextField;

  /**
   * HowTime field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.howtime
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  howtime: prismic.KeyTextField;

  /**
   * Feeling field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.feeling
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feeling: prismic.KeyTextField;

  /**
   * ToldAnyone field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.toldanyone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  toldanyone: prismic.KeyTextField;

  /**
   * ReceivedTherapy field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.receivedtherapy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  receivedtherapy: prismic.KeyTextField;

  /**
   * Message field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * ButtonSend field in *Text → ContactTurno → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.contactTurno.primary.buttonsend
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonsend: prismic.KeyTextField;
}

/**
 * ContactTurno variation for Text Slice
 *
 * - **API ID**: `contactTurno`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceContactTurno = prismic.SharedSliceVariation<
  "contactTurno",
  Simplify<TextBlockSliceContactTurnoPrimary>,
  never
>;

/**
 * Primary content in *Text → PreguntaFrecuente → Primary*
 */
export interface TextBlockSlicePreguntaFrecuentePrimary {
  /**
   * Title field in *Text → PreguntaFrecuente → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.preguntaFrecuente.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Text → PreguntaFrecuente → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.preguntaFrecuente.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Text → Items*
 */
export interface TextBlockSlicePreguntaFrecuenteItem {
  /**
   * TitleFaq field in *Text → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.items[].titlefaq
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titlefaq: prismic.KeyTextField;

  /**
   * DescriptionFaq field in *Text → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.items[].descriptionfaq
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descriptionfaq: prismic.KeyTextField;
}

/**
 * PreguntaFrecuente variation for Text Slice
 *
 * - **API ID**: `preguntaFrecuente`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlicePreguntaFrecuente = prismic.SharedSliceVariation<
  "preguntaFrecuente",
  Simplify<TextBlockSlicePreguntaFrecuentePrimary>,
  Simplify<TextBlockSlicePreguntaFrecuenteItem>
>;

/**
 * Primary content in *Text → Author → Primary*
 */
export interface TextBlockSliceAuthorPrimary {
  /**
   * Author field in *Text → Author → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ingrese autor
   * - **API ID Path**: text_block.author.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Text field in *Text → Author → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ingrese el texto
   * - **API ID Path**: text_block.author.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Author variation for Text Slice
 *
 * - **API ID**: `author`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceAuthor = prismic.SharedSliceVariation<
  "author",
  Simplify<TextBlockSliceAuthorPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTitleText
  | TextBlockSliceAuthorTitleText
  | TextBlockSliceFirma
  | TextBlockSliceShortTextDiario
  | TextBlockSliceContactText
  | TextBlockSliceContactTurno
  | TextBlockSlicePreguntaFrecuente
  | TextBlockSliceAuthor;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      CopyrightDocument,
      CopyrightDocumentData,
      GlobalSettingsDocument,
      GlobalSettingsDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavleftItem,
      NavigationDocumentDataNavrightItem,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutMeSlice,
      AboutMeSliceDefaultPrimary,
      AboutMeSliceVariation,
      AboutMeSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceImageTextPrimary,
      ImageBlockSliceImageParagraphPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      ImageBlockSliceImageText,
      ImageBlockSliceImageParagraph,
      PictureButtonSlice,
      PictureButtonSliceDefaultPrimary,
      PictureButtonSliceDefaultItem,
      PictureButtonSliceSameStylePrimary,
      PictureButtonSliceSameStyleItem,
      PictureButtonSliceVariation,
      PictureButtonSliceDefault,
      PictureButtonSliceSameStyle,
      SectionCheckSlice,
      SectionCheckSliceDefaultPrimary,
      SectionCheckSliceDefaultItem,
      SectionCheckSliceVariation,
      SectionCheckSliceDefault,
      SectionContentSlice,
      SectionContentSliceDefaultPrimary,
      SectionContentSliceDefaultItem,
      SectionContentSliceVariation,
      SectionContentSliceDefault,
      SectionTextSlice,
      SectionTextSliceDefaultPrimary,
      SectionTextSliceStaticPrimary,
      SectionTextSliceImageWithFrasePrimary,
      SectionTextSliceImageWithTwoFrasesPrimary,
      SectionTextSliceStaticLargePrimary,
      SectionTextSliceVariation,
      SectionTextSliceDefault,
      SectionTextSliceStatic,
      SectionTextSliceImageWithFrase,
      SectionTextSliceImageWithTwoFrases,
      SectionTextSliceStaticLarge,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceTitleTextPrimary,
      TextBlockSliceAuthorTitleTextPrimary,
      TextBlockSliceFirmaPrimary,
      TextBlockSliceShortTextDiarioPrimary,
      TextBlockSliceContactTextPrimary,
      TextBlockSliceContactTurnoPrimary,
      TextBlockSlicePreguntaFrecuentePrimary,
      TextBlockSlicePreguntaFrecuenteItem,
      TextBlockSliceAuthorPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockSliceTitleText,
      TextBlockSliceAuthorTitleText,
      TextBlockSliceFirma,
      TextBlockSliceShortTextDiario,
      TextBlockSliceContactText,
      TextBlockSliceContactTurno,
      TextBlockSlicePreguntaFrecuente,
      TextBlockSliceAuthor,
    };
  }
}
