// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  nav_left: dynamic(() => import("./NavLeft")),
  nav_right: dynamic(() => import("./NavRight")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  picture_button: dynamic(() => import("./PictureButton")),
  section_check: dynamic(() => import("./SectionCheck")),
  section_content: dynamic(() => import("./SectionContent")),
  section_text: dynamic(() => import("./SectionText")),
};
