// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  copyright: dynamic(() => import("./Copyright")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  nav_left: dynamic(() => import("./NavLeft")),
  nav_right: dynamic(() => import("./NavRight")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  picture_button: dynamic(() => import("./PictureButton")),
  section_check: dynamic(() => import("./SectionCheck")),
  section_content: dynamic(() => import("./SectionContent")),
  section_text: dynamic(() => import("./SectionText")),
  text_block: dynamic(() => import("./TextBlock")),
};
