// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  picture_button: dynamic(() => import("./PictureButton")),
  section_check: dynamic(() => import("./SectionCheck")),
  section_content: dynamic(() => import("./SectionContent")),
  section_text: dynamic(() => import("./SectionText")),
  text_block: dynamic(() => import("./Textos")),
};
