// import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';
// import styles from '@/styles/Home.module.css';

// const inter = Inter({ subsets: ['latin'] });

// export default function Home(props) {
//   const { page, menu } = props;
//   console.log(page);
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <meta name='viewport' content='width=device-width, initial-scale=1' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <p>wara</p>
//       </main>
//     </>
//   );
// }
import Head from 'next/head';
import { SliceZone } from '@prismicio/react';
import * as prismicH from '@prismicio/helpers';

import { createClient } from '../prismicio';
import { components } from '../slices/';
import { Layout } from '../components/Layout';

const Index = ({ page, navigation, settings }) => {
  return (
    <Layout navigation={navigation} settings={settings}>
      {/* <Head>
        <title>{prismicH.asText(page.data.title)}</title>
      </Head> */}
      <SliceZone slices={page.data.slices} components={components} />
    </Layout>
  );
};

export default Index;

export async function getStaticProps({ locale, previewData }) {
  const client = createClient({ previewData });

  const page = await client.getByUID('page', 'home', { lang: locale });
  const navigation = await client.getSingle('navigation', { lang: locale });
  // const settings = await client.getSingle('settings', { lang: locale });

  return {
    props: {
      page,
      navigation,
      // settings,
    },
  };
}
